### ISSUE TITLE
node crashes in virtualbox

### ISSUE THREAD

**Issue by dafyk** [nray-scanner/nray#11] opened 2019-09-24 10:32 UTC
When running node in Virtualbox (running debian) node crashes with following error:

```
INFO[2019-09-24T04:18:21-05:00] Connecting to: tcp://localhost:8601           module=core.messageQueue src=InitServerConnection
INFO[2019-09-24T04:18:21-05:00] Got ID: efce55d8                              module=core.messageStuff src=HandleRegisteredNode
INFO[2019-09-24T04:18:21-05:00] Requesting work batch                         module=scanner.scanner src=RunNodeScannerLoop
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x804a32c]

goroutine 21 [running]:
runtime/internal/atomic.Xadd64(0x57a6530c, 0x1, 0x0, 0x0, 0x0)
        /usr/lib/go/src/runtime/internal/atomic/asm_386.s:105 +0xc
github.com/nray-scanner/nray/scanner.RunNodeScannerLoop.func1(0x57a65290, 0x57ac5f10, 0x57a71d40)
        /home/eder/code/nray-scanner/nray/scanner/scanner.go:69 +0x5b
created by github.com/nray-scanner/nray/scanner.RunNodeScannerLoop
        /home/eder/code/nray-scanner/nray/scanner/scanner.go:67 +0x56d

```

**Comment by edermi** [comment] 2019-09-24 20:57
Thanks for reaching out!

Unfortunately, I can't reproduce the issue with my setup:

- Windows 10 host, latest virtualbox
- Debian 10, fresh patches installed and rebooted as guest
- nray 1.0.1 from releases page

I run `nray-x64-linux server -c nray-conf.yaml` and `nray node` next to it - works like a charm.

Can you give more information? Which version/branch and which binary (32/64 bit) of nray are you using? Which configuration file do you use? Anything else to help me reproduce the issue?

While developing the pre-prototype of nray I saw a similar error once; as far as I recall it was a 32 bit binary crashing on x64 for some weird reason, but at some point that bug went away so I didn't spend more time on investigating.

**Comment by edermi** [comment] 2019-12-16 12:15
No feedback received, closing issue

**Closed by edermi** 2019-12-16 12:15 UTC
