### ISSUE TITLE
go build fails. make also.

### ISSUE THREAD

**Issue by new-gen23** [nray-scanner/nray#14] opened 2020-01-11 12:59 UTC
Running "go build" I get:
`nray.go:5:2: cannot find package "github.com/nray-scanner/nray/cmd" in any of:
	/usr/lib/go-1.10/src/github.com/nray-scanner/nray/cmd (from $GOROOT)
	/home/user/go/src/github.com/nray-scanner/nray/cmd (from $GOPATH)`

Running "make" I get:
`mkdir -p ./build
cp nray-conf.yaml ./build/
go build -race -ldflags "-X main.server=127.0.0.1 -X main.port=8601" -o build/nray_localhardcoded ./nray.go 
nray.go:5:2: cannot find package "github.com/nray-scanner/nray/cmd" in any of:
	/usr/lib/go-1.10/src/github.com/nray-scanner/nray/cmd (from $GOROOT)
	/home/user/go/src/github.com/nray-scanner/nray/cmd (from $GOPATH)
Makefile:18: recipe for target 'build-localarch' failed
make: *** [build-localarch] Error 1`

I would assume that the format of the path in nray.go is somehow wrong formatted? I have no skill with go yet, but it looks to me like he is searching the URL on the local harddisc.

**Comment by new-gen23** [comment] 2020-01-11 13:01
Btw. the path "https://github.com/nray-scanner/nray/cmd" will produce 404 not found. It's located in "https://github.com/nray-scanner/nray/tree/master/cmd". (It might also be I just don't understand the git path structure).

**Comment by edermi** [comment] 2020-01-14 08:01
Since nray uses Go modules, you need at least Go 1.11 and Go modules enabled. 
You may checkout the latest development branch and use the Docker container there to verify that the build works.

**Comment by edermi** [comment] 2020-03-07 22:04
Cannot reproduce, no feedback given - closing this issue

**Closed by edermi** 2020-03-07 22:04 UTC
